<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
	</PropertyGroup>
	<PropertyGroup>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.2" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.2" />
		<PackageReference Include="Syncfusion.Blazor.Grid" Version="28.2.5" />
		<PackageReference Include="Syncfusion.Blazor.Themes" Version="28.2.5" />
		<PackageReference Include="Syncfusion.Blazor.MultiColumnCombobox" Version="28.2.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Backend\Cenitu.Security.DataAccess\Cenitu.Security.DataAccess.csproj" />
		<ProjectReference Include="..\..\..\MiddleWares\Cenitu.Security.Dtos\Cenitu.Security.Dtos.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\SfResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>SfResources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Shared.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Shared.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\SfResources.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>SfResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Shared.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Shared.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
